?>
<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=device-width, initial-scale=1"> <meta name="description" content=""> <meta name="author" content=""> <title>Validacion de Facebook</title>
 <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"> <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'> <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'> <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet"> <link href="css/creative.min.css" rel="stylesheet"> </head> <body id="page-top"> <nav id="mainNav" class="navbar navbar-default navbar-fixed-top"> <div class="container-fluid"> <div class="navbar-header"> <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
   
   <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i> </button> <a class="navbar-brand page-scroll" href="#page-top">Prestappme</a> </div> <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> <ul class="nav navbar-nav navbar-right"> <li> <a class="page-scroll" 
  
     <a class="page-scroll" href="../index.php">cerrar sesion</a> </li> </ul> </div> </div> </nav> <header> <div class="header-content"> <div class="header-content-inner"> 
  <h1 id="homeHeading">PRESTAPPME</h1> <hr> <a href="#about" class="btn btn-primary btn-xl page-scroll">Continua como Julio</a> </div> </div> </header> <section class="bg-primary" id="about"> <div class="container"> <div class="row"> <div class="col-lg-8 col-lg-offset-2 text-center"> <h1 class="section-heading">Facebook hara una Evaluacion de tu Perfil.</h1> 
  <hr class="light"> 
  <p class="text-faded">En un lapso de 48 horas se te notificara si fuiste aceptado. </p> 
  </div>
   <div class="col-lg-8 col-lg-offset-2 text-center">
    <h1 class="section-heading">Si Fuiste Aceptado</h1> <hr class="light"> <p class="text-faded"> se te enviara un codigo de verificacion a tu celular</p> </div> </div> </div> </section>
     <row no-gutter popup-gallery> <div class="col-lg-4 col-sm-6"> <a href="img/portfolio/fullsize/1.jpg" class="portfolio-box"> <img src="img/portfolio/thumbnails/1.jpg" class="img-responsive" alt=""> </a> </div> <div class="col-lg-4 col-sm-6"> <a href="img/portfolio/fullsize/2.jpg" class="portfolio-box"> <img src="img/portfolio/thumbnails/2.jpg" class="img-responsive" alt=""> </a> </div> <div class="col-lg-4 col-sm-6"> <a href="img/portfolio/fullsize/3.jpg" class="portfolio-box"> <img src="img/portfolio/thumbnails/3.jpg" class="img-responsive" alt=""> </a> </div> <div class="col-lg-4 col-sm-6"> <a href="img/portfolio/fullsize/4.jpg" class="portfolio-box"> <img src="img/portfolio/thumbnails/4.jpg" class="img-responsive" alt=""> </a> </div> <div class="col-lg-4 col-sm-6"> <a href="img/portfolio/fullsize/5.jpg" class="portfolio-box"> <img src="img/portfolio/thumbnails/5.jpg" class="img-responsive" alt=""> </a> </div> <div class="col-lg-4 col-sm-6"> <a href="img/portfolio/fullsize/6.jpg" class="portfolio-box"> <img src="img/portfolio/thumbnails/6.jpg" class="img-responsive" alt=""> </a> </div> </div> </div> </section> <section id="contact"> <div class="container"> <div class="row"> <div class="col-lg-8 col-lg-offset-2 text-center"><script src="vendor/jquery/jquery.min.js"></script> <script src="vendor/bootstrap/js/bootstrap.min.js"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script> <script src="vendor/scrollreveal/scrollreveal.min.js"></script> <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script> <script src="js/creative.min.js"></script> </body> </html> 
<?php